Jenkinsfile
hemera-dev-values.yaml

Add hamera-dev values in fullstack-pro to add env variables and prevent out of memory issue

Add hamera-dev values in fullstack-pro to add env variables and prevent out of memory issue 

---

Jenkinsfile

Add blueocean build url in slack notification

Add blueocean build url in slack notification

---

Jenkinsfile

Issue#319 Enable hyperlink in slack notification

Issue#319 Enable hyperlink in slack notification

---

Jenkinsfile
hemera-dev-values.yaml
servers/frontend-server/src/config/apollo-client.ts
servers/hemera-server/charts/hemera-server/.helmignore
servers/hemera-server/charts/hemera-server/Chart.yaml
servers/hemera-server/charts/hemera-server/templates/NOTES.txt
servers/hemera-server/charts/hemera-server/templates/_helpers.tpl
servers/hemera-server/charts/hemera-server/templates/deployment.yaml
servers/hemera-server/charts/hemera-server/templates/ingress.yaml
servers/hemera-server/charts/hemera-server/templates/mongodb-external-service.yaml
servers/hemera-server/charts/hemera-server/templates/nats-external-service.yaml
servers/hemera-server/charts/hemera-server/templates/redis-external-service.yaml
servers/hemera-server/charts/hemera-server/templates/service.yaml
servers/hemera-server/charts/hemera-server/values.yaml

Restore hemera-server helm chart in this repo locally

Restore hemera-server helm chart in this repo locally

---

Jenkinsfile

Remove ghprbSourcebanch variables as we will handle this in future PR

Remove ghprbSourcebanch variables as we will handle this in future PR

---

Jenkinsfile

Add global variable for git branch

Add global variable for git branch

---

Jenkinsfile
package-lock.json

Fix DNS issue for stage

---

servers/backend-server/src/connectors/redis-connector.ts
servers/frontend-server/.zenrc.js

Add testfile to test PR status

Add testfile to test PR status

---

Jenkinsfile

This merge request is created to work Jenkinsfile with master-slave arch.
Below are the detailed changes.
1) GPG keys are mounted in Jenkins-slave to unlock secrets in runtime.
2) Change `getDirs` function to work on slave.
NOTE: 
1) **After merge of this request, This pipeline will no longer works in old Jenkins (Single Master).** Because of GPG.

Change Jenkinsfile to work with master-slave architecture.

---

Jenkinsfile

Add github repo token for deployment

Add github repo token for deployment

---

Jenkinsfile

Add helm init before repo add

---

servers/moleculer-server/charts/chart/templates/deployment.yaml
servers/moleculer-server/charts/chart/templates/ingress.yaml

Upgrade Helm Kubernetes templates to 1.16 capable version.

Upgrade Helm Kubernetes templates to 1.16 capable version.

---

Jenkinsfile

Add choice parameter in Jenkinsfile to select idestack chart version

Add choice parameter in Jenkinsfile to select idestack chart version

---

package-lock.json
package.json
servers/moleculer-server/charts/chart/templates/deployment.yaml
servers/moleculer-server/charts/chart/templates/ingress.yaml

Upgrade Jenkinsfile to work with Kubernetes 1.18x

Upgrade Jenkinsfile to work with Kubernetes 1.18x

---

Jenkinsfile

Swap idestack default version

---

Jenkinsfile

Namespace logic to handle namespace before installing helm install

Namespace logic to handle namespace before installing helm install

---

Jenkinsfile

Fix namespace logic check feature

Fix namespace logic check feature

---

Jenkinsfile

This PR is created against issue no 211.
Apart from that, New chart is generated with version 0.3.0 to consume updated changes.

remove hardcoded ideback and idefront (Issue: #211)

---

Jenkinsfile

Change production doamin to cdebase.com from cdebase.io

Change production doamin to cdebase.com from cdebase.io

---

Jenkinsfile

Remove docker tools as it is no longer required

Remove docker tools as it is no longer required

---

Jenkinsfile
Jenkinsfile_new_1
Jenkinsfile_old

Add new Jenkins pipeline workflow

Add new Jenkins pipeline workflow

---

Jenkinsfile

Merge Jenkinsfile changes to the master branch manually.

Merge Jenkinsfile changes to the master branch manually.

---

Jenkinsfile

Conditionlize master branch to handle prod deployments

Conditionlize master branch to handle prod deployments

---

Jenkinsfile

Modify some conditions to master branch

Modify some conditions to master branch

---

Jenkinsfile

Fix branch merge failing issue

Fix branch merge failing issue

---

Jenkinsfile

Remove extra checkout command

---

Jenkinsfile

Roll out new changes to fullstack

Roll out new changes to fullstack

---

Jenkinsfile

Rollout stage changes to the Jenkins

Rollout stage changes to the Jenkins

---

Jenkinsfile

Update Jenkinsfile conditions according to the requirements

Update Jenkinsfile conditions according to the requirements

---

Jenkinsfile

Add stage env and new conditions as requested in github issue

Add stage env and new conditions as requested in github issue

---

Jenkinsfile

Rollout conditional changes to the master branch

Rollout conditional changes to the master branch

---

portable-devices/desktop/src/main/utils/window/protocol.ts

Resolved electron production build issue

Resolved electron production build issue

---

Jenkinsfile

Reverts CDEBase/fullstack-pro#316

Revert "Drive namespace from BASE_NAMESPACE and VERSION"
